services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - /postgresql/data
  redis:
    image: redis:alpine3.17
    env_file:
      - .env
    ports:
      - '6379:6379'