services:
  db-test:
    image: postgres:14.1-alpine
    env_file:
      - ../.env
    ports:
      - '9876:5432'
    volumes:
      - /postgresql/data-test
  redis-test:
    image: redis:alpine3.17
    env_file:
      - ../.env
    ports:
      - '6378:6379'